### ISSUE TITLE
Generate a docker image to run application locally

### ISSUE THREAD

**Issue by Tugark** [gipfeli-io/gipfeli-docker#3]
Tobias asked us to provide him with an easy way to run the application locally. We want to try to setup a docker image to start the application.

**Comment by Saela** [comment]
Unfortunately I was not able to run the docker environment on my machine. Pulling the images seems to work fine but when I try to execute docker compose up I get this weird error:

![Image](https://user-images.githubusercontent.com/14041976/184362611-f5b2a9be-1c74-47e3-99a6-382de6d3560c.png)

**Comment by Tugark** [comment]
@Saela Sorry, my bad. I could reproduce it, I forgot to add the step with the submodules. You have to actually init and update them so that their content is loaded. Otherwise, they do not have content and this error appears.

Can you please try again by deleting your current clone, and follow the steps here: https://github.com/gipfeli-io/gipfeli-docker#installation

Afterwards, configuration is the same.

**Comment by Saela** [comment]
@Tugark Now it works thank you. :D 

Some issues I found:

- If you use the local environment which does not have the possibility to send emails you have to manually activate the users in the database. We should highlight this.
- If you already accessed e.g. the staging environment or used the application locally => if the indexeddb version does not match there will be an error and you have to clean the database. We should also highlight this.
- We should also mention that when you copy the env.example file you should remove all of the # comments after variables

As for the local environment, I would add the following steps to make it easy to activate the users:

- Open a terminal
- Enter docker ps
- Find postgres docker container
- Exec into this container (e.g. Docker Container id = 449b381db88c => docker exec -it 449b381db88c bash)
- Execute psql -U postgres -W
- Enter the password (postgres)
- Execute UPDATE public.user SET "isActive"=true;

We should provide Tobias with pre-configured .env files so he is faster in setting everything up.

If you agree with my suggestions I will update the documentation. :)

**Comment by Tugark** [comment]
> @Tugark Now it works thank you. :D
> 
> Some issues I found:
> 
> * If you use the local environment which does not have the possibility to send emails you have to manually activate the users in the database. We should highlight this.

See below, you're right.

> * If you already accessed e.g. the staging environment or used the application locally => if the indexeddb version does not match there will be an error and you have to clean the database. We should also highlight this.

Good catch (and screw offline functionality XD). Is this the error?
![image](https://user-images.githubusercontent.com/16555423/188082911-6a6ef857-85dc-43c4-8436-ce2d4571ddae.png)
-> If so, we should add a hint on what needs to be cleared, or just add a hint to use our built-in cleanup functionality under http://localhost:3001/profile

> * We should also mention that when you copy the env.example file you should remove all of the # comments after variables

I guess we could add this to the project repositories anyway, good point.

> As for the local environment, I would add the following steps to make it easy to activate the users:
> 
> * Open a terminal
> * Enter docker ps
> * Find postgres docker container
> * Exec into this container (e.g. Docker Container id = 449b381db88c => docker exec -it 449b381db88c bash)
> * Execute psql -U postgres -W
> * Enter the password (postgres)
> * Execute UPDATE public.user SET "isActive"=true;

There is an even simpler way because we already have a wizard 🧙 You have to log into the `gipfeli-docker_backend` container and then run the wizard:
```
$ docker exec -it 891da7d386f4 sh # <- notice the "sh" command, we don't have bash installed
$ npm run create-user
```
The wizard then allows you to create whatever user you want :)

> We should provide Tobias with pre-configured .env files so he is faster in setting everything up.

Totally, especially with the whole base64 part for the google account.

> If you agree with my suggestions I will update the documentation. :)

Yes, thank you :D

**Comment by Saela** [comment]
@Tugark done 🚀🥐 I also added the info about the env file to the readme's of the other repositories.
